package supervisor

import (
	"fmt"
	"os"
	"path/filepath"
	"text/template"
)

// MariaDBConfig represents the configuration for MariaDB.
type MariaDBConfig struct {
	Port              int
	DataDir           string
	LogFile           string
	InnoDBBufferPoolSize int
	MaxConnections    int
}

// startMariaDB starts the MariaDB database server inside proot.
func (s *Supervisor) startMariaDB() error {
	// Ensure required directories exist
	dataDir := filepath.Join(s.rootfsPath, "var/lib/mysql")
	logPath := filepath.Join(s.logDir, "mysql")
	
	if err := os.MkdirAll(dataDir, 0755); err != nil {
		return fmt.Errorf("failed to create mysql data directory: %w", err)
	}
	if err := os.MkdirAll(logPath, 0755); err != nil {
		return fmt.Errorf("failed to create mysql log directory: %w", err)
	}

	// Calculate InnoDB buffer pool size based on allocated RAM
	// Use 25% of allocated RAM for InnoDB
	bufferPoolSize := s.config.Resources.RAMMB * 25 / 100
	if bufferPoolSize < 64 {
		bufferPoolSize = 64 // Minimum 64MB
	}
	if bufferPoolSize > 512 {
		bufferPoolSize = 512 // Cap at 512MB for mobile
	}

	// Generate my.cnf from template
	configPath := filepath.Join(s.rootfsPath, "etc/mysql/my.cnf")
	if err := s.writeMariaDBConfig(configPath, bufferPoolSize); err != nil {
		return fmt.Errorf("failed to write mariadb config: %w", err)
	}

	// Check if database needs initialization
	if !s.isMariaDBInitialized(dataDir) {
		if err := s.initializeMariaDB(dataDir, configPath); err != nil {
			return fmt.Errorf("failed to initialize mariadb: %w", err)
		}
	}

	// Build the start command
	cmd := s.buildProotCommand(
		"mysqld",
		"--defaults-file="+configPath,
		"--user=mysql",
		"--datadir="+dataDir,
	)

	// Redirect stdout/stderr to log files
	logFile := filepath.Join(logPath, "mysql.log")
	logOutput, err := os.OpenFile(logFile, os.O_CREATE|os.O_WRONLY|os.O_APPEND, 0644)
	if err != nil {
		return fmt.Errorf("failed to open mysql log: %w", err)
	}

	cmd.Stdout = logOutput
	cmd.Stderr = logOutput

	// Start with max 3 restarts
	return s.startService("mariadb", cmd, 3)
}

// isMariaDBInitialized checks if the MariaDB data directory is initialized.
func (s *Supervisor) isMariaDBInitialized(dataDir string) bool {
	// Check for the mysql system database
	mysqlDir := filepath.Join(dataDir, "mysql")
	_, err := os.Stat(mysqlDir)
	return err == nil
}

// initializeMariaDB initializes a new MariaDB database cluster.
func (s *Supervisor) initializeMariaDB(dataDir, configPath string) error {
	// Run mysql_install_db to initialize the database
	initCmd := s.buildProotCommand(
		"mysql_install_db",
		"--defaults-file="+configPath,
		"--user=mysql",
		"--datadir="+dataDir,
	)

	output, err := initCmd.CombinedOutput()
	if err != nil {
		return fmt.Errorf("mysql_install_db failed: %w, output: %s", err, string(output))
	}

	return nil
}

// writeMariaDBConfig writes the MariaDB configuration file.
func (s *Supervisor) writeMariaDBConfig(path string, bufferPoolSize int) error {
	cfg := &MariaDBConfig{
		Port:                 s.config.Resources.Ports.MySQL,
		DataDir:              filepath.Join(s.rootfsPath, "var/lib/mysql"),
		LogFile:              filepath.Join(s.logDir, "mysql/mysql.log"),
		InnoDBBufferPoolSize: bufferPoolSize,
		MaxConnections:       50, // Reasonable limit for mobile
	}

	// Ensure parent directory exists
	dir := filepath.Dir(path)
	if err := os.MkdirAll(dir, 0755); err != nil {
		return fmt.Errorf("failed to create config directory: %w", err)
	}

	file, err := os.Create(path)
	if err != nil {
		return fmt.Errorf("failed to create config file: %w", err)
	}
	defer file.Close()

	tmpl := template.Must(template.New("my.cnf").Parse(mariaDBConfigTemplate))
	if err := tmpl.Execute(file, cfg); err != nil {
		return fmt.Errorf("failed to execute template: %w", err)
	}

	return nil
}

const mariaDBConfigTemplate = `# MariaDB configuration for PocketServer
# Generated by pocketd - do not edit manually

[client]
port = {{.Port}}
socket = /tmp/mysql.sock

[mysql]
default-character-set = utf8mb4

[mysqld]
# Basic settings
port = {{.Port}}
socket = /tmp/mysql.sock
datadir = {{.DataDir}}
user = mysql

# Character set
character-set-server = utf8mb4
collation-server = utf8mb4_unicode_ci

# InnoDB settings
innodb_buffer_pool_size = {{.InnoDBBufferPoolSize}}M
innodb_log_file_size = 64M
innodb_flush_log_at_trx_commit = 2
innodb_flush_method = O_DIRECT

# Connection settings
max_connections = {{.MaxConnections}}
max_allowed_packet = 16M

# Logging
log_error = {{.LogFile}}
slow_query_log = 1
slow_query_log_file = {{.LogFile}}.slow
long_query_time = 2

# Binary logging for replication
log_bin = /var/log/mysql/mysql-bin.log
binlog_format = ROW
expire_logs_days = 7
max_binlog_size = 100M

# Security
skip-symbolic-links
local-infile = 0

# Performance
table_open_cache = 200
thread_cache_size = 10
query_cache_type = 1
query_cache_size = 32M
query_cache_limit = 2M

# Temp tables
tmp_table_size = 32M
max_heap_table_size = 32M

# Bind to localhost only for security
bind-address = 127.0.0.1
`
