package supervisor

import (
	"fmt"
	"os"
	"path/filepath"
	"text/template"
)

// NginxConfig represents the configuration for Nginx.
type NginxConfig struct {
	WorkerProcesses int
	WorkerConnections int
	HTTPPort        int
	HTTPSPort       int
	LogPath         string
	ProjectsDir     string
}

// startNginx starts the Nginx web server inside proot.
func (s *Supervisor) startNginx() error {
	// Ensure required directories exist
	logPath := filepath.Join(s.logDir, "nginx")
	if err := os.MkdirAll(logPath, 0755); err != nil {
		return fmt.Errorf("failed to create nginx log directory: %w", err)
	}

	// Generate nginx.conf from template
	configPath := filepath.Join(s.rootfsPath, "etc/nginx/nginx.conf")
	if err := s.writeNginxConfig(configPath); err != nil {
		return fmt.Errorf("failed to write nginx config: %w", err)
	}

	// Test configuration before starting
	testCmd := s.buildProotCommand("nginx", "-t", "-c", configPath)
	if output, err := testCmd.CombinedOutput(); err != nil {
		return fmt.Errorf("nginx config test failed: %w, output: %s", err, string(output))
	}

	// Build the start command
	cmd := s.buildProotCommand(
		"nginx",
		"-c", configPath,
		"-g", "daemon off;",
	)

	// Redirect stdout/stderr to log files
	accessLog := filepath.Join(logPath, "access.log")
	errorLog := filepath.Join(logPath, "error.log")

	accessFile, err := os.OpenFile(accessLog, os.O_CREATE|os.O_WRONLY|os.O_APPEND, 0644)
	if err != nil {
		return fmt.Errorf("failed to open access log: %w", err)
	}

	errorFile, err := os.OpenFile(errorLog, os.O_CREATE|os.O_WRONLY|os.O_APPEND, 0644)
	if err != nil {
		accessFile.Close()
		return fmt.Errorf("failed to open error log: %w", err)
	}

	cmd.Stdout = accessFile
	cmd.Stderr = errorFile

	// Start with max 3 restarts
	return s.startService("nginx", cmd, 3)
}

// writeNginxConfig writes the nginx configuration file.
func (s *Supervisor) writeNginxConfig(path string) error {
	cfg := &NginxConfig{
		WorkerProcesses:   1, // Mobile device, not a server
		WorkerConnections: 256,
		HTTPPort:          s.config.Resources.Ports.HTTP,
		HTTPSPort:         s.config.Resources.Ports.HTTPS,
		LogPath:           filepath.Join(s.logDir, "nginx"),
		ProjectsDir:       s.projectsDir,
	}

	// Ensure parent directory exists
	dir := filepath.Dir(path)
	if err := os.MkdirAll(dir, 0755); err != nil {
		return fmt.Errorf("failed to create config directory: %w", err)
	}

	file, err := os.Create(path)
	if err != nil {
		return fmt.Errorf("failed to create config file: %w", err)
	}
	defer file.Close()

	tmpl := template.Must(template.New("nginx.conf").Parse(nginxConfigTemplate))
	if err := tmpl.Execute(file, cfg); err != nil {
		return fmt.Errorf("failed to execute template: %w", err)
	}

	return nil
}

// ReloadNginx reloads the Nginx configuration without stopping the server.
func (s *Supervisor) ReloadNginx() error {
	pm, ok := s.services["nginx"]
	if !ok {
		return fmt.Errorf("nginx service not found")
	}

	pm.mu.RLock()
	pid := pm.pid
	pm.mu.RUnlock()

	if pid <= 0 {
		return fmt.Errorf("nginx is not running")
	}

	// Send SIGHUP to reload configuration
	if err := pm.cmd.Process.Signal(os.Interrupt); err != nil {
		return fmt.Errorf("failed to signal nginx: %w", err)
	}

	return nil
}

const nginxConfigTemplate = `# Nginx configuration for PocketServer
# Generated by pocketd - do not edit manually

user www-data;
worker_processes {{.WorkerProcesses}};
pid /tmp/nginx.pid;
error_log {{.LogPath}}/error.log warn;

events {
    worker_connections {{.WorkerConnections}};
    use epoll;
    multi_accept on;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    # Logging format
    log_format main '$remote_addr - $remote_user [$time_local] "$request" '
                    '$status $body_bytes_sent "$http_referer" '
                    '"$http_user_agent" "$http_x_forwarded_for" '
                    'rt=$request_time uct="$upstream_connect_time" '
                    'uht="$upstream_header_time" urt="$upstream_response_time"';

    access_log {{.LogPath}}/access.log main;

    # Performance optimizations
    sendfile on;
    tcp_nopush on;
    tcp_nodelay on;
    keepalive_timeout 65;
    types_hash_max_size 2048;

    # Security headers
    server_tokens off;
    add_header X-Frame-Options "DENY" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header X-XSS-Protection "1; mode=block" always;

    # Gzip compression
    gzip on;
    gzip_vary on;
    gzip_proxied any;
    gzip_comp_level 6;
    gzip_types text/plain text/css text/xml application/json application/javascript application/xml;

    # Include virtual hosts
    include /etc/nginx/sites-enabled/*.conf;
}
`
