package supervisor

import (
	"fmt"
	"os"
	"path/filepath"
	"text/template"
)

// NodeJSConfig represents the configuration for Node.js applications.
type NodeJSConfig struct {
	AppPath     string
	Port        int
	LogFile     string
	MaxMemory   int // in MB
}

// startNodeJS starts a Node.js application inside proot.
// Note: This is a placeholder implementation as Node.js support is optional.
func (s *Supervisor) startNodeJS() error {
	// Check if there's a Node.js project to run
	// For Phase 1, we just verify Node.js is available
	// Full implementation will come in Phase 2 with project management
	
	// Ensure required directories exist
	logPath := filepath.Join(s.logDir, "nodejs")
	if err := os.MkdirAll(logPath, 0755); err != nil {
		return fmt.Errorf("failed to create nodejs log directory: %w", err)
	}

	// For now, we'll just verify node is available in the rootfs
	testCmd := s.buildProotCommand("node", "--version")
	if output, err := testCmd.CombinedOutput(); err != nil {
		// Node.js not installed yet - this is OK for Phase 1
		// Return nil to allow startup to continue
		return nil
	} else {
		// Log that Node.js is available
		_ = output // Will be used when we implement actual Node.js projects
	}

	// Node.js projects will be started per-project in Phase 2
	// For now, we don't start a global Node.js process
	return nil
}

// StartNodeJSProject starts a specific Node.js project.
// This will be fully implemented in Phase 2.
func (s *Supervisor) StartNodeJSProject(projectSlug, appPath string, port int) error {
	logPath := filepath.Join(s.logDir, "nodejs")
	
	cfg := &NodeJSConfig{
		AppPath:   appPath,
		Port:      port,
		LogFile:   filepath.Join(logPath, fmt.Sprintf("%s.log", projectSlug)),
		MaxMemory: s.config.Resources.RAMMB * 20 / 100, // 20% of allocated RAM
	}

	// Ensure log directory exists
	if err := os.MkdirAll(logPath, 0755); err != nil {
		return fmt.Errorf("failed to create nodejs log directory: %w", err)
	}

	// Build the start command
	cmd := s.buildProotCommand(
		"node",
		appPath,
	)

	// Set environment variables
	cmd.Env = append(cmd.Env,
		fmt.Sprintf("PORT=%d", port),
		fmt.Sprintf("NODE_ENV=production"),
	)

	// Redirect stdout/stderr to log files
	logOutput, err := os.OpenFile(cfg.LogFile, os.O_CREATE|os.O_WRONLY|os.O_APPEND, 0644)
	if err != nil {
		return fmt.Errorf("failed to open nodejs log: %w", err)
	}

	cmd.Stdout = logOutput
	cmd.Stderr = logOutput

	// Start with max 3 restarts
	serviceName := fmt.Sprintf("nodejs-%s", projectSlug)
	return s.startService(serviceName, cmd, 3)
}

// writeNodeJSConfig writes a Node.js PM2-style configuration file.
// This is used for managing multiple Node.js applications.
func (s *Supervisor) writeNodeJSConfig(path string, projects []NodeJSConfig) error {
	dir := filepath.Dir(path)
	if err := os.MkdirAll(dir, 0755); err != nil {
		return fmt.Errorf("failed to create config directory: %w", err)
	}

	file, err := os.Create(path)
	if err != nil {
		return fmt.Errorf("failed to create config file: %w", err)
	}
	defer file.Close()

	tmpl := template.Must(template.New("ecosystem.config.js").Parse(nodejsConfigTemplate))
	if err := tmpl.Execute(file, projects); err != nil {
		return fmt.Errorf("failed to execute template: %w", err)
	}

	return nil
}

const nodejsConfigTemplate = `// Node.js PM2 ecosystem configuration for PocketServer
// Generated by pocketd - do not edit manually

module.exports = {
  apps: [
{{- range $i, $proj := . }}
    {
      name: "app-{{$i}}",
      script: "{{$proj.AppPath}}",
      instances: 1,
      exec_mode: "fork",
      env: {
        NODE_ENV: "production",
        PORT: {{$proj.Port}},
      },
      max_memory_restart: "{{$proj.MaxMemory}}M",
      error_file: "{{$proj.LogFile}}.error",
      out_file: "{{$proj.LogFile}}.out",
      log_file: "{{$proj.LogFile}}.combined",
      time: true,
    },
{{- end }}
  ]
};
`
