package supervisor

import (
	"fmt"
	"os"
	"path/filepath"
	"text/template"
)

// PHPFPMConfig represents the configuration for PHP-FPM.
type PHPFPMConfig struct {
	PoolName      string
	Listen        string
	User          string
	Group         string
	MaxChildren   int
	StartServers  int
	MinSpareServers int
	MaxSpareServers int
	MaxRequests   int
	RequestTerminateTimeout int
	LogFile       string
}

// startPHPFPM starts the PHP-FPM process manager inside proot.
func (s *Supervisor) startPHPFPM() error {
	// Ensure required directories exist
	logPath := filepath.Join(s.logDir, "php")
	if err := os.MkdirAll(logPath, 0755); err != nil {
		return fmt.Errorf("failed to create php log directory: %w", err)
	}

	// Calculate max children based on allocated RAM
	// Formula from spec: floor(ram_mb * 0.4 / 25)
	maxChildren := (s.config.Resources.RAMMB * 40 / 100) / 25
	if maxChildren < 2 {
		maxChildren = 2
	}
	if maxChildren > 16 {
		maxChildren = 16 // Cap for mobile devices
	}

	// Generate php-fpm.conf from template
	configPath := filepath.Join(s.rootfsPath, "etc/php8/php-fpm.d/www.conf")
	if err := s.writePHPFPMConfig(configPath, maxChildren); err != nil {
		return fmt.Errorf("failed to write php-fpm config: %w", err)
	}

	// Build the start command
	cmd := s.buildProotCommand(
		"php-fpm8",
		"--nodaemonize",
		"--fpm-config", filepath.Join(s.rootfsPath, "etc/php8/php-fpm.conf"),
	)

	// Redirect stdout/stderr to log files
	logFile := filepath.Join(logPath, "php-fpm.log")
	logOutput, err := os.OpenFile(logFile, os.O_CREATE|os.O_WRONLY|os.O_APPEND, 0644)
	if err != nil {
		return fmt.Errorf("failed to open php-fpm log: %w", err)
	}

	cmd.Stdout = logOutput
	cmd.Stderr = logOutput

	// Start with max 3 restarts
	return s.startService("php-fpm", cmd, 3)
}

// writePHPFPMConfig writes the PHP-FPM pool configuration file.
func (s *Supervisor) writePHPFPMConfig(path string, maxChildren int) error {
	cfg := &PHPFPMConfig{
		PoolName:                "www",
		Listen:                  "/tmp/php-fpm.sock",
		User:                    "www-data",
		Group:                   "www-data",
		MaxChildren:             maxChildren,
		StartServers:            maxChildren / 4,
		MinSpareServers:         maxChildren / 8,
		MaxSpareServers:         maxChildren / 2,
		MaxRequests:             500,
		RequestTerminateTimeout: 30,
		LogFile:                 filepath.Join(s.logDir, "php/php-fpm.log"),
	}

	// Ensure parent directory exists
	dir := filepath.Dir(path)
	if err := os.MkdirAll(dir, 0755); err != nil {
		return fmt.Errorf("failed to create config directory: %w", err)
	}

	file, err := os.Create(path)
	if err != nil {
		return fmt.Errorf("failed to create config file: %w", err)
	}
	defer file.Close()

	tmpl := template.Must(template.New("www.conf").Parse(phpfpmConfigTemplate))
	if err := tmpl.Execute(file, cfg); err != nil {
		return fmt.Errorf("failed to execute template: %w", err)
	}

	return nil
}

const phpfpmConfigTemplate = `[{{.PoolName}}]
; PHP-FPM pool configuration for PocketServer
; Generated by pocketd - do not edit manually

; Pool name
pool = {{.PoolName}}

; User and group
user = {{.User}}
group = {{.Group}}

; Socket configuration
listen = {{.Listen}}
listen.owner = www-data
listen.group = www-data
listen.mode = 0660

; Process management settings
pm = dynamic
pm.max_children = {{.MaxChildren}}
pm.start_servers = {{.StartServers}}
pm.min_spare_servers = {{.MinSpareServers}}
pm.max_spare_servers = {{.MaxSpareServers}}
pm.max_requests = {{.MaxRequests}}

; Request timeout
request_terminate_timeout = {{.RequestTerminateTimeout}}

; Logging
catch_workers_output = yes
php_admin_value[error_log] = {{.LogFile}}
php_flag[log_errors] = on

; Security restrictions
php_admin_value[open_basedir] = /var/www:/tmp
php_admin_value[disable_functions] = exec,passthru,shell_exec,system,proc_open,popen,curl_exec,curl_multi_exec,parse_ini_file,show_source

; Environment variables
env[TMP] = /tmp
env[TMPDIR] = /tmp
env[TEMP] = /tmp
`
