package supervisor

import (
	"fmt"
	"os"
	"path/filepath"
	"text/template"
)

// RedisConfig represents the configuration for Redis.
type RedisConfig struct {
	Port        int
	BindAddress string
	LogFile     string
	MaxMemory   int // in MB
}

// startRedis starts the Redis server inside proot.
func (s *Supervisor) startRedis() error {
	// Ensure required directories exist
	logPath := filepath.Join(s.logDir, "redis")
	if err := os.MkdirAll(logPath, 0755); err != nil {
		return fmt.Errorf("failed to create redis log directory: %w", err)
	}

	// Calculate max memory based on allocated RAM (use 10% for Redis)
	maxMemory := s.config.Resources.RAMMB * 10 / 100
	if maxMemory < 32 {
		maxMemory = 32 // Minimum 32MB
	}
	if maxMemory > 256 {
		maxMemory = 256 // Cap at 256MB for mobile
	}

	// Generate redis.conf from template
	configPath := filepath.Join(s.rootfsPath, "etc/redis/redis.conf")
	if err := s.writeRedisConfig(configPath, maxMemory); err != nil {
		return fmt.Errorf("failed to write redis config: %w", err)
	}

	// Build the start command
	cmd := s.buildProotCommand(
		"redis-server",
		configPath,
	)

	// Redirect stdout/stderr to log files
	logFile := filepath.Join(logPath, "redis.log")
	logOutput, err := os.OpenFile(logFile, os.O_CREATE|os.O_WRONLY|os.O_APPEND, 0644)
	if err != nil {
		return fmt.Errorf("failed to open redis log: %w", err)
	}

	cmd.Stdout = logOutput
	cmd.Stderr = logOutput

	// Start with max 3 restarts
	return s.startService("redis", cmd, 3)
}

// writeRedisConfig writes the Redis configuration file.
func (s *Supervisor) writeRedisConfig(path string, maxMemory int) error {
	bindAddress := "127.0.0.1"
	if !s.config.Network.BindLocalhostOnly {
		bindAddress = "0.0.0.0"
	}

	cfg := &RedisConfig{
		Port:        s.config.Resources.Ports.Redis,
		BindAddress: bindAddress,
		LogFile:     filepath.Join(s.logDir, "redis/redis.log"),
		MaxMemory:   maxMemory,
	}

	// Ensure parent directory exists
	dir := filepath.Dir(path)
	if err := os.MkdirAll(dir, 0755); err != nil {
		return fmt.Errorf("failed to create config directory: %w", err)
	}

	file, err := os.Create(path)
	if err != nil {
		return fmt.Errorf("failed to create config file: %w", err)
	}
	defer file.Close()

	tmpl := template.Must(template.New("redis.conf").Parse(redisConfigTemplate))
	if err := tmpl.Execute(file, cfg); err != nil {
		return fmt.Errorf("failed to execute template: %w", err)
	}

	return nil
}

const redisConfigTemplate = `# Redis configuration for PocketServer
# Generated by pocketd - do not edit manually

# Network
bind {{.BindAddress}}
port {{.Port}}
protected-mode yes
tcp-backlog 511
timeout 0
tcp-keepalive 300

# General
daemonize no
supervised no
pidfile /tmp/redis.pid
loglevel notice
logfile {{.LogFile}}
databases 16

# Snapshotting
save 900 1
save 300 10
save 60 10000
stop-writes-on-bgsave-error yes
rdbcompression yes
rdbchecksum yes
dbfilename dump.rdb
dir /tmp

# Memory management
maxmemory {{.MaxMemory}}mb
maxmemory-policy allkeys-lru

# Append only mode
appendonly no
appendfilename "appendonly.aof"
appendfsync everysec
no-appendfsync-on-rewrite no
auto-aof-rewrite-percentage 100
auto-aof-rewrite-min-size 64mb

# Replication
replica-serve-stale-data yes
replica-read-only yes
repl-diskless-sync no
repl-ping-replica-period 10
repl-timeout 60

# Security
# requirepass is set dynamically via command line if needed

# Clients
maxclients 100

# Lazy freeing
lazyfree-lazy-eviction no
lazyfree-lazy-expire no
lazyfree-lazy-server-del no
replica-lazy-flush no

# Slow log
slowlog-log-slower-than 10000
slowlog-max-len 128

# Latency monitor
latency-monitor-threshold 0

# Event notification
notify-keyspace-events ""

# Advanced config
hash-max-ziplist-entries 512
hash-max-ziplist-value 64
list-max-ziplist-size -2
list-compress-depth 0
set-max-intset-entries 512
zset-max-ziplist-entries 128
zset-max-ziplist-value 64
hll-sparse-max-bytes 3000
stream-node-max-bytes 4096
stream-node-max-entries 100
activerehashing yes
client-output-buffer-limit normal 0 0 0
client-output-buffer-limit replica 256mb 64mb 60
client-output-buffer-limit pubsub 32mb 8mb 60
hz 10
dynamic-hz yes
aof-rewrite-incremental-fsync yes
rdb-save-incremental-fsync yes
`
